sonar.projectKey=crms-devops_crms
sonar.organization=crms-devops
sonar.projectName=CRMS
sonar.sources=backend/app,frontend/src
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.13
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/tests/**